language: java

install: true

before_install:
  - echo "Downloading Maven"
  - wget https://dlcdn.apache.org/maven/maven-3/3.8.2/binaries/apache-maven-3.8.2-bin.tar.gz
  - echo "Installing Maven"
  - tar xzvf apache-maven-3.8.2-bin.tar.gz
  - echo "Adding Paths"
  - export MAVEN_HOME=`pwd`/apache-maven-3.8.2
  - export PATH=${MAVEN_HOME}/bin:${PATH}
  - mvn -v

script:
  - cd ${TRAVIS_BUILD_DIR}/modules/set-game
  - mvn clean package
  - cd ${TRAVIS_BUILD_DIR}/modules/example-opennlp
  - mvn clean package
  - cd ${TRAVIS_BUILD_DIR}/modules/tree-traversal
  - mvn clean package
  - cd ${TRAVIS_BUILD_DIR}/modules/browser
  - mvn clean package

jdk:
  - openjdk16

notifications:
  email:
    - false
