language: java
install: true
script:
  - cd ${TRAVIS_BUILD_DIR}/modules/set-game
  - mvn clean package
  - cd ${TRAVIS_BUILD_DIR}/modules/example-opennlp
  - mvn clean package
  - cd ${TRAVIS_BUILD_DIR}/modules/tree-traversal
  - mvn clean package

jdk:
  - openjdk15

sudo: false

notifications:
  email:
    - false
