version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/openjdk:16.0

jobs:
  reusable-job:
    description: "Reusable Job which takes working directory as a parameter"
    docker:
      - image: cimg/openjdk:16.0
    parameters:
      wd:
        description: "To pass in the working directory"
        type: string
    steps:
      - checkout
      - run:
          working_directory: << parameters.wd >>
          command: mvn clean package
    
  Set Game:
    executor: default-executor
    steps:
      - checkout
      - run:
          working_directory: modules/set-game
          command: mvn clean package

  Concordance:
    executor: default-executor
    steps:
      - checkout
      - run:
          working_directory: modules/example-opennlp
          command: mvn clean package

  Tree Traversal:
    executor: default-executor
    steps:
      - checkout
      - run:
          working_directory: modules/tree-traversal
          command: mvn clean package

  Browser:
    executor: default-executor
    steps:
      - checkout
      - run:
          working_directory: modules/browser
          command: mvn clean package

workflows:
  default: 
    jobs:
      - reusable-job:
          name: Concordance
          wd: modules/example-opennlp
      - Set Game
      - Tree Traversal
      - Browser
