# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "Build"

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        module: [
          {
            name: 'Concordance',
            wd: 'modules/example-opennlp'
          },
          {
            name: 'Set Game',
            wd: 'modules/set-game'
          },
          {
            name: 'Tree Traversal',
            wd: 'modules/tree-traversal'
          },
          {
            name: 'Browser',
            wd: 'modules/browser'
          }
        ]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven

    - name: Build '${{ matrix.module.name }}' with Maven
      working-directory: ${{ matrix.module.wd }}
      run: mvn clean package
